version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=devops2
    ports:
      - "3306:3306"
  springboot-docker-container:
    image: fadhelbh/springcontainer
    links: 
      - mysql-standalone:app_db
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://app_db:3306/devops2?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: ""
    build:
      context: "./"
      dockerfile: "dockerfile"
    depends_on: 
      - mysql-standalone